### ISSUE TITLE
Add an option to create mailboxes from AD users

### ISSUE THREAD

**Issue by tigre-bleu** [aleemladha/ludus_exchange#2]
It would be nice to have an option to add mailboxes for existing AD users.

Simple version would be to just add a mailbox for every existing user.

Enhanced version would be to use template vars to select which users to add. For instance:

```
     roles:
       - aleemladha.ludus_exchange
     role_vars:
       ludus_exchange_domain_username: VULNCORP\ludus-adm0
       ludus_exchange_domain_password: somepassword
       ludus_exchange_mailboxes:
         - user1
         - user2
         - user3
```

At the moment only the user from `ludus_exchange_domain_username` gets a mailbox.
